root_data : '/media/reinstate/MyData1/code/datasets/'
dir_ckpts : '/media/reinstate/MyData1/code/mnist-mlops/ckpts'
mflow_tracking_uri : "sqlite:///mlflow.db"
mlflow_experiment_name : "mlops-mnist-pl"
mlflow_artifact_path : "pytorch-model"
classes : 10
epochs : 1
percent_valid_examples : 0.1
batch_size : 128
tune_trials : 100
tune_timeout : 20